### ISSUE TITLE
Setup Problem

### ISSUE THREAD

**Issue by blink1073** [takluyver/redsnail#9]
I tried to test it out:
From a clean checkout:

``` bash
rm -r pypkgs/
rm: cannot remove ‘pypkgs/’: No such file or directory
make: *** [deps] Error 1
```

If I change that to `rm -rf pypkgs/` I get:

``` bash
Successfully installed tornado terminado certifi ptyprocess
Cleaning up...
rm -r pypkgs/*.egg-info
bower install
make: *** [deps] Error 1
```

I have `bower@1.3.12 node_modules/bower`, `pip 1.5.6` (Python 3.4), and `GNU Make 3.81` on Linux Mint 17 64 bit.

**Comment by takluyver** [comment]
Does 'bower install' give you an error message? Someone got it set up OK
yesterday after making the rm -rf change, so it's not something specific to
my computer.

**Comment by blink1073** [comment]
Sorry, this got lost in the shuffle.  I'm on OSX now, and the install works fine.
